import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import TestBox from "../components/testBox";
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="p-4 min-h-screen flex flex-col justify-center items-center">
        <h1 className="text-3xl font-bold underline decoration-wavy">
          Hello World Pedro Serrano Web!
        </h1>

        <TestBox />
      </main>
    </div>
  );
};

export default Home;
